### ISSUE TITLE
No such key: PasswordPolicyOptions

### ISSUE THREAD

**Issue by pragmaticT** [jamfit/Current-User-Password-Age#2]
Doesn't seem to be running accurately against 10.11.6

**Comment by jamfit** [comment]
A proposed fix has been committed here:

https://github.com/jamfit/Current-User-Password-Age/tree/bug/IndexError-list-index-out-of-range

There is a change in how errors are returned as a `<result>` in this version. Check the README for more details.

This should address the "No such key" issue and still return a result. Please add additional comments onto #1.
